export enum Color {
  Primary = "#7B61FF",
  Primary_Light = "#917CFF",
  Secondary = "#80858B",
  Black = "#000000",
  Dark = "#242426",
  Graphite = "#323537",
  Error = "#FF5154",
  Light = "#AFB2B6",
  White = "#FFFFFF",
  Green = "#00A340",
  Yellow = "#F3A608",
  Orange = "#F45D2D",
  Errors = "#FF5154",
  Primary_BG = "var(--bg-primary)",
  Primary_TX = "var(--primary)",
  Primary_TEXT = "var(--primary-text)",
  Primary_TEXT_LIGHT = "var(--primary-text-light)",
  Primary_INPUT_BG = "var(--primary-input-bg)",
  Primary_INPUT_BORDER = "var(--primary-input-border)",
  Primary_FORM_BG = "var(--primary-form-bg)",
  Label_Text = "var(--label-text)",
}
